### ISSUE TITLE
Support for models with partial layers frozen 

### ISSUE THREAD

**Issue by dhuruvasaditya** [Enealor/PyTorch-SM3#19]
I am trying to fine-tune GPT-Neo-1.3B model using SM3. Since I have less data I dont want to train the whole model but only the top 12 Decoder blocks of it. 
I do it by using:

```
for parameter in model.parameters():
    parameter.requires_grad = False

for i, m in enumerate(model.transformer.h):        
    #Only un-freeze the last n transformer blocks
    if i >= 10:
        for parameter in m.parameters():
            parameter.requires_grad = True 
```

But this leads to problem in SM3.py wherein 
```
for p in group['params']:
    if p is None:
        continue
    grad = p.grad

    state = self.state[p]
    shape = grad.shape #error here
    rank = len(shape)
```
None has not attriibute shape

Would be really helpful if this functionality is added.

**Comment by Enealor** [comment]
Thank you for informing me of this issue. I made an MR to resolve it: https://github.com/Enealor/PyTorch-SM3/pull/20. Does this solution work for your use case?

**Comment by dhuruvasaditya** [comment]
Yes works perfectly now! Many thanks! +1:

**Comment by dhuruvasaditya** [comment]
Yes works perfectly now! Many thanks!
